# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='用户uid')),
                ('nick', models.CharField(max_length=255, null=True, unique=True, verbose_name='用户昵称')),
                ('email', models.CharField(max_length=255, null=True, unique=True, verbose_name='注册邮箱')),
                ('phone_number', models.IntegerField(null=True, unique=True, verbose_name='注册手机号')),
                ('face_image', models.ImageField(default='Images/None/default-img.jpg', upload_to='Images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
